use crate::tui::app::SingleAsciiIconState;

const TRIM_BOX_PRESENT: &[&str] = &[
    "       HH                                   HH       ",
    "       HH                                   HH       ",
    "     __HH___________________________________HH__     ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  BM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  BM]    ",
    " MMM___  ___________________________________  ___MMM ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMM|``````mMH|`````.HMH|  _____]DMH  DM]    ",
    "    [MH  DMM|  MMM, MH|  MM,  DH|  [DMMMMMMH  DM]    ",
    "    [MH  DMM|  MM,  MH|  MM,  DH|  [DMMMMMMH  DM]    ",
    "    [MH  DMM|     MMMH|  MM,  DH|  ____DMMMH  DM]    ",
    "    [MH  DMM|  DMMMMMH|  MM,  DH|  MMMMMMMMH  DM]    ",
    "    [MH  DMM|__DMMMMMH|____'HMMH|__MMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMM|````````````|MMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMM| {subtitle} |MMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMM|____________|MMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  DM]    ",
    " MMM___  ___________________________________  ___MMM ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  BM]    ",
    "    [MH  DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH  BM]    ",
    "    ```HH```````````````````````````````````HH```    ",
    "       HH                                   HH       ",
    "       HH                                   HH       ",
];

const NO_TRIM_BOX: &[&str] = &[
    "                                                     ",
    "                                                     ",
    "     ___________________________________________     ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMM|``````mMH|`````.HMH|  _____]DMMMMMM]    ",
    "    [MMMMMMM|  MMM, MH|  MM,  DH|  [DMMMMMMMMMMM]    ",
    "    [MMMMMMM|  MM,  MH|  MM,  DH|  [DMMMMMMMMMMM]    ",
    "    [MMMMMMM|     MMMH|  MM,  DH|  ____DMMMMMMMM]    ",
    "    [MMMMMMM|  DMMMMMH|  MM,  DH|  MMMMMMMMMMMMM]    ",
    "    [MMMMMMM|__DMMMMMH|____'HMMH|__MMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMM|````````````|MMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMM| {subtitle} |MMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMM|____________|MMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMM\\ \\vVMVMVv/ /MMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMm\\ \\vKM/ /MMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMm\\ `` /MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMM/ /a\\ \\MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMM/ /mMAMm\\ \\MMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MM/_/mMMMMMMMm\\_\\MMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    `````````````````````````````````````````````    ",
    "                                                     ",
    "                                                     ",
];

const INVALID_PDF: &[&str] = &[
    "                                                     ",
    "                                                     ",
    "     ___________________________________________     ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMQQQQQQQQMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMV/   \\VMMMMMMH]       klMMMMMMMMMMM]    ",
    "    [MMMMMMMH]     [DMMMMMMMmmmmmo\\   klMMMMMMMM]    ",
    "    [MMMMMMMH]     [DMMMMMMMMMMMMMMO   .mMMMMMMM]    ",
    "    [MMMMMMMH]     [DMMMMMMMMMMMMMMM> .MMMMMMMMM]    ",
    "    [MMMMMMMH]     [DMMMMMMMMMMMMM'  /MMMMMMMMMM]    ",
    "    [MMMMMMMH]     [DMMMMMMMMMMMMl  /MMMMMMMMMMM]    ",
    "    [MMMMMMMMA\\   /AMMMMMMH]````___kMMMMMMMMMMMM]    ",
    "    [MMMMMMMMH]   [HMMMMMMH]   [DMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMH]   [HMMMMMMH]   [DMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMH]   [HMMMMMMH]   [DMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMOOOMMMMMMMMMMOOMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMH]```[DMMMMMMH]```[DMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMH]___[DMMMMMMH]___[DMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    `````````````````````````````````````````````    ",
    "                                                     ",
    "                                                     ",
];

const LOADING: &[&str] = &[
    "                                                     ",
    "                                                     ",
    "     ___________________________________________     ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMM]``````[MMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMG`  \\VMMM]      [MMv/    `GMMMMMMMM]    ",
    "    [MMMMMMa`      \\VU        UV/       aMMMMMMM]    ",
    "    [MMMMMMMa                          aMMMMMMMM]    ",
    "    [MMMMMMMMb                        dMMMMMMMMM]    ",
    "    [MMMMMMMMMm        AMMMMA        mMMMMMMMMMM]    ",
    "    [MMMM|````      /MMMMMMMMM\\       `````|MMMM]    ",
    "    [MMMM|         (GMMMMMMMMMMO)          |MMMM]    ",
    "    [MMMM|___      (<MMMMMMMMMM>)       ___|MMMM]    ",
    "    [MMMMMMMMm,     \\OMMMMMMMMO/      ,mMMMMMMMM]    ",
    "    [MMMMMMMM/        \\VMMMMV/         vMMMMMMMM]    ",
    "    [MMMMMMM'          ``````            VMMMMMM]    ",
    "    [MMMMv`                                \\VMMM]    ",
    "    [MMMMMMA      /aMMa       gMMa       mMMMMMM]    ",
    "    [MMMMMMMAm   AMMMH]       [HMMMA    mMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMH]_______[HMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    `````````````````````````````````````````````    ",
    "                                                     ",
    "                                                     ",
];

const FAILED_TO_LOAD: &[&str] = &[
    "                                                     ",
    "                                                     ",
    "     ___________________________________________     ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMBs``.WMMMMMMMMMMMMMMMMMMMMP``sGMMMMMM]    ",
    "    [MMMMMMMGn.  .WMMMMMMMMMMMMMMMB.   dGMMMMMMM]    ",
    "    [MMMMMMMMMGn.  .WMMMMMMMMMMMB.   dGMMMMMMMMM]    ",
    "    [MMMMMMMMMMMGn.  .WMMMMMMMB.   dGMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMGn.  .WMMMB.   dGMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMGn.   VV   dGMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMa       dGMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMV/       \\VMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMbp   /AA\\   qdMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMbp   onMMMMMno   qdMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMbp    onMMMMMMMMno   qdMMMMMMMMMM]    ",
    "    [MMMMMMMMbp   onMMMMMMMMMMMMMno   qdMMMMMMMM]    ",
    "    [MMMMMMbp    onMMMMMMMMMMMMMMMMno   qdMMMMMM]    ",
    "    [MMMMMMN^`_onMMMMMMMMMMMMMMMMMMMMno_`^NMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    [MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]    ",
    "    `````````````````````````````````````````````    ",
    "                                                     ",
    "                                                     ",
];

pub fn icon_lines(state: &SingleAsciiIconState, subtitle: &str) -> Vec<String> {
    let raw: &[&str] = match state {
        SingleAsciiIconState::TrimBoxPresent => TRIM_BOX_PRESENT,
        SingleAsciiIconState::PureCMYK => TRIM_BOX_PRESENT,
        SingleAsciiIconState::PureRGB => TRIM_BOX_PRESENT,
        SingleAsciiIconState::NoTrimBox => NO_TRIM_BOX,
        SingleAsciiIconState::InvalidPdf => INVALID_PDF,
        SingleAsciiIconState::Loading => LOADING,
        SingleAsciiIconState::FailedToLoad => FAILED_TO_LOAD,
        // Action states stubbed as loading art for now
        SingleAsciiIconState::ResizingToBleed => LOADING,
        SingleAsciiIconState::ExportImages => LOADING,
        SingleAsciiIconState::DeleteTrimMarks => LOADING,
    };

    let effective_subtitle = match state {
        SingleAsciiIconState::PureCMYK => "CMYK",
        SingleAsciiIconState::PureRGB => "RGB",
        _ => subtitle,
    };

    raw.iter()
        .map(|line| line.replace("{subtitle}", effective_subtitle))
        .collect()
}
