use rand::seq::IndexedRandom;

pub fn random_quip() -> String {
    let quips: Vec<&'static str> = vec![
        "Hello World!",
        "Thinking happy thoughts...",
        "Drinking morning coffee",
        "VI VII VI VII VI VII",
        "Drinking matcha",
        "Bing Chilling",
        "Left the stove on",
        "Drinking tea",
        "Acting like a dang fool",
        "Had an \"Ackshully!\" moment",
        "Being a lil goober",
        "Ate some chicken nuggets",
        "Forgot to flush",
        "Solved a rubiks cube",
        "Discovering the mysteries of the cosmos",
        "Forgot to shave",
        "Tax evasion",
        "Idk man... uh...",
        "A New Hand Touches The Beacon",
        "Running out of ideas",
        "Need a break from the ads?",
        "In a galaxy far far away...",
        "FAHHHHHH",
        "Playing DnD",
        "Rolled a Nat 1",
        "Rolled a Nat 20",
        "Roll for Initiative",
        "Got beat by Magnus Carlsen in Chess",
        "Using vim",
        "Using vim (I don't know how to exit)",
        "Reminiscing on vine...",
        "Using Twitt- I mean... X",
        "Ate a donut",
        "Yippee!!!",
        "Finishing season 6 of Stranger Things",
        "Finding the answer to Life, The Universe, Everything",
        "42",
        "Inappropriate jokes about horses",
        "Dapped up my homies",
        "I forgor...",
        "Getting a cold one with the boys",
        "Chicken Jockey",
        "World domination (in Minecraft)",
        "Insurance fraud",
        "Remembered to breath",
        "Ate ice cream",
        "Spilt my beans ;(",
        "Ate pizza",
        "Did a thing",
        "Went deep into my thoughts",
        "Went on a heist (in GTA V)",
        "Random quip generator before GTA VI",
        "0110111101101011",
        "Forgot my keys",
        "Fell down but got back up",
        "Reached the end of my limits",
        "Belief in myself (Good ending)",
        "Believing in myself (Canon ending)",
        "Believed in myself (Bad ending)",
        "Got beat by Hikaru Nakamura in Chess",
        "Leveled up!",
        "Rooting for my team",
        "Had szechuan sauce",
        "Trying to say worcestershire sauce",
        "Say Drake!",
        "Took care of business",
        "Go StL Cardinals!",
        "Go Blues!",
        "Reached the farlands",
        "Fought the Ender dragon",
        "Met a celebrity",
        "Swam the ocean blue",
        "Spotted the enemy",
        "I frew up",
        "Wanting to pet that dog",
        "Pet a puppy/dog",
        "Pet a kitten/cat",
        "Pet a gerbil",
        "Pet a hamster",
        "Pet a rabbit",
        "Pet a snake",
        "Fed the doggo",
        "Fed the destroyer (cat)",
        "Made memories",
        "Flew to the moon",
        "Played among the stars",
        "Had a power-level over 9000",
        "Burnt my shake",
        "Wait, I'm alive!",
        "Had a Piña colada",
        "Forgot to save",
        "Gotta catch 'em all!",
        "Went on an adventure",
        "Cried over spilled milk",
        "Saved a princess",
        "The princess is in another castle",
        "Got shwifty",
        "Did the stanky leg",
        "Built a car",
        "Boiled some eggs",
        "Watched a Youtube video",
    ];
    let mut rnd = rand::rng();
    quips.choose(&mut rnd).unwrap().to_string()
}
